import UIKit

// MARK: - CrashPlaygroundVC

/// Manual crash trigger (guarded), UI freeze simulation, non-fatal error generation.
/// SAFETY: fatalError must always be behind UIAlertController confirmation.
final class CrashPlaygroundVC: UIViewController {

    private let logger: EventLogger

    // MARK: - Init

    init(logger: EventLogger) {
        self.logger = logger
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder: NSCoder) { fatalError() }

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Crash & Error Playground"
        view.backgroundColor = .systemBackground
        setupLayout()
    }

    // MARK: - Layout

    private func setupLayout() {
        let warningBanner = makeBanner(
            text: "⚠️  These controls trigger real crashes, UI freezes, and error events. Use only to validate RUM SDK crash/error capture.",
            color: .systemRed
        )

        let crashBtn    = makeDangerButton(title: "💥  Trigger Crash (fatalError)", action: #selector(triggerCrash))
        let freezeBtn   = makeWarnButton(title: "🧊  Freeze UI (5s ANR simulation)", action: #selector(triggerFreeze))
        let nonFatalBtn = makeActionButton(title: "⚡  Generate Non-Fatal Error", action: #selector(triggerNonFatal))

        let stack = UIStackView(arrangedSubviews: [warningBanner, crashBtn, freezeBtn, nonFatalBtn])
        stack.axis = .vertical
        stack.spacing = 16
        stack.layoutMargins = UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
        stack.isLayoutMarginsRelativeArrangement = true
        stack.translatesAutoresizingMaskIntoConstraints = false

        view.addSubview(stack)
        NSLayoutConstraint.activate([
            stack.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            stack.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            stack.trailingAnchor.constraint(equalTo: view.trailingAnchor),
        ])
    }

    // MARK: - Actions

    /// SAFETY GUARD: fatalError is ALWAYS behind UIAlertController confirmation.
    @objc private func triggerCrash() {
        let alert = UIAlertController(
            title: "Trigger crash?",
            message: "This will immediately terminate the app. The RUM SDK should capture a crash report. Only proceed to test crash detection.",
            preferredStyle: .alert
        )
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
        alert.addAction(UIAlertAction(title: "Crash", style: .destructive) { _ in
            fatalError("[RUMSimulator] Intentional test crash")
        })
        present(alert, animated: true)
    }

    /// Freezes the main thread for 5 seconds to trigger ANR/hang detection.
    @objc private func triggerFreeze() {
        let alert = UIAlertController(
            title: "Freeze UI?",
            message: "This will block the main thread for 5 seconds to simulate an ANR hang. The RUM SDK should detect the hang.",
            preferredStyle: .alert
        )
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel))
        alert.addAction(UIAlertAction(title: "Freeze", style: .destructive) { _ in
            Thread.sleep(forTimeInterval: 5)
        })
        present(alert, animated: true)
    }

    /// Generates a non-fatal NSError and logs it via EventLogger.
    @objc private func triggerNonFatal() {
        let error = NSError(
            domain: "RUMSimulator",
            code: 42,
            userInfo: [
                NSLocalizedDescriptionKey: "Intentional non-fatal test error",
                NSLocalizedFailureReasonErrorKey: "Generated by Crash & Error Playground"
            ]
        )
        logger.log(
            type: "crash",
            metadata: [
                "error_domain": error.domain,
                "error_code": "\(error.code)",
                "error_description": error.localizedDescription,
                "fatal": "false"
            ]
        )

        let alert = UIAlertController(
            title: "Non-fatal Error Generated",
            message: "Error logged: \(error.domain) code \(error.code). Check the Event Log to verify.",
            preferredStyle: .alert
        )
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        present(alert, animated: true)
    }

    // MARK: - UI Factories

    private func makeBanner(text: String, color: UIColor) -> UIView {
        let container = UIView()
        container.backgroundColor = color.withAlphaComponent(0.1)
        container.layer.cornerRadius = 12
        container.layer.borderWidth = 1
        container.layer.borderColor = color.withAlphaComponent(0.3).cgColor

        let label = UILabel()
        label.text = text
        label.numberOfLines = 0
        label.font = .systemFont(ofSize: 13, weight: .medium)
        label.textColor = color
        label.translatesAutoresizingMaskIntoConstraints = false
        container.addSubview(label)
        NSLayoutConstraint.activate([
            label.topAnchor.constraint(equalTo: container.topAnchor, constant: 12),
            label.bottomAnchor.constraint(equalTo: container.bottomAnchor, constant: -12),
            label.leadingAnchor.constraint(equalTo: container.leadingAnchor, constant: 14),
            label.trailingAnchor.constraint(equalTo: container.trailingAnchor, constant: -14),
        ])
        return container
    }

    private func makeDangerButton(title: String, action: Selector) -> UIButton {
        var config = UIButton.Configuration.filled()
        config.title = title
        config.cornerStyle = .medium
        config.baseBackgroundColor = .systemRed
        let b = UIButton(configuration: config)
        b.addTarget(self, action: action, for: .touchUpInside)
        b.heightAnchor.constraint(equalToConstant: 50).isActive = true
        return b
    }

    private func makeWarnButton(title: String, action: Selector) -> UIButton {
        var config = UIButton.Configuration.filled()
        config.title = title
        config.cornerStyle = .medium
        config.baseBackgroundColor = .systemOrange
        let b = UIButton(configuration: config)
        b.addTarget(self, action: action, for: .touchUpInside)
        b.heightAnchor.constraint(equalToConstant: 50).isActive = true
        return b
    }

    private func makeActionButton(title: String, action: Selector) -> UIButton {
        var config = UIButton.Configuration.tinted()
        config.title = title
        config.cornerStyle = .medium
        let b = UIButton(configuration: config)
        b.addTarget(self, action: action, for: .touchUpInside)
        b.heightAnchor.constraint(equalToConstant: 50).isActive = true
        return b
    }
}
